### ISSUE TITLE
If upstream call fails throw exception as well

### ISSUE THREAD

**Issue by tomasfejfar** [tomasfejfar/datetime-strict#1]
The expression \DateTime::createFromFor...mat, $time, $timezone); of type DateTime|false adds false to the return on line 27 which is incompatible with the return type documented by TomasFejfar\DateTime\Dat...trict::createFromFormat of type DateTime.

**Comment by tomasfejfar** [comment]
I'd like the method to throw exception as well if the internal `createFromFormat` returns `false`.

**Comment by aautar** [comment]
Seemed simple:
https://github.com/tomasfejfar/datetime-strict/pull/2

However, I couldn't find a case where `\DateTime::createFromFormat()` returns false, but there are no warning or errors. If you know of a case, I can write a test.

**Comment by tomasfejfar** [comment]
You are certainly right. But I thought that it would be a nice to handle the edge case anyway to make it futureproof. Also I thought it would be a nice easy pullrequest for someone to do for hacktoberfest :)
